name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:        # allow manual run

permissions:
  contents: write   # ✅ allow pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Save cookies
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Update YouTube sources
        run: |
          mkdir -p sources

          # --- Define YouTube channels with metadata ---
          declare -A CHANNELS=(
            ["arise-news|Arise News|https://marvellye.github.io/iptv/images/arise-news-logo-lg.png|News|"]="https://www.youtube.com/watch?v=srJg6ZIPmvU"
            ["sky-news|Sky News|https://marvellye.github.io/iptv/images/Sky_News.png.png|News|SkyNews.uk"]="https://www.youtube.com/watch?v=YDvsBbKfLPA"
            ["tvc-news|TVC News|https://marvellye.github.io/iptv/images/TVC_News.png|News|TvcNews.ng"]="https://www.youtube.com/watch?v=Mv14aabg4mA"
          )

          for META in "${!CHANNELS[@]}"; do
            URL=${CHANNELS[$META]}
            FILE=$(echo "$META" | cut -d'|' -f1)
            NAME=$(echo "$META" | cut -d'|' -f2)
            LOGO=$(echo "$META" | cut -d'|' -f3)
            GROUP=$(echo "$META" | cut -d'|' -f4)
            TVGID=$(echo "$META" | cut -d'|' -f5)

            echo "#EXTM3U" > sources/$FILE.m3u

            # Try to fetch stream link with cookies
            M3U_URL=$(yt-dlp --cookies cookies.txt -g -f "301/300/94/93/92/91" "$URL" 2>/dev/null || echo "")

            if [ -n "$M3U_URL" ]; then
              echo "#EXTINF:-1 tvg-id=\"$TVGID\" tvg-logo=\"$LOGO\" group-title=\"$GROUP\",$NAME" >> sources/$FILE.m3u
              echo "$M3U_URL" >> sources/$FILE.m3u
            else
              echo "#EXTINF:-1 tvg-id=\"$TVGID\" tvg-logo=\"$LOGO\" group-title=\"$GROUP\",$NAME (Unavailable)" >> sources/$FILE.m3u
              echo "http://offline" >> sources/$FILE.m3u
            fi
          done

      - name: Build master & playlist
        run: |
          # Build master: static + raw streams
          cp static.m3u master.m3u
          for f in sources/*.m3u; do
            tail -n +2 "$f" >> master.m3u
          done

          # Build playlist: static + references to sources (with metadata)
          cp static.m3u playlist.m3u
          for f in sources/*.m3u; do
            FILE=$(basename "$f")
            EXTINF=$(grep -m1 "#EXTINF" "$f")
            echo "$EXTINF" >> playlist.m3u
            echo "https://raw.githubusercontent.com/${{ github.repository }}/main/sources/$FILE" >> playlist.m3u
          done

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add master.m3u playlist.m3u sources/*.m3u
          git commit -m "Auto update IPTV playlist" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main