name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:        # allow manual run

permissions:
  contents: write   # ✅ allow pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Save cookies
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Update YouTube sources
        run: |
          mkdir -p sources

          # --- Define YouTube channels with metadata ---
          declare -A CHANNELS=(
            ["arise-news|Arise News|https://marvellye.github.io/iptv/images/arise-news-logo-lg.png|News|"]="https://www.youtube.com/AriseNewsChannel/live"
            ["sky-news|Sky News|https://marvellye.github.io/iptv/images/Sky_News.png.png|News|SkyNews.uk"]="https://www.youtube.com/SkyNews/live"
            ["tvc-news|TVC News|https://marvellye.github.io/iptv/images/TVC_News.png|News|TvcNews.ng"]="https://www.youtube.com/tvcnewsnigeria/live"
            ["channels-tv|Channels TV|https://marvellye.github.io/iptv/images/Channels_TV.png|News|ChannelsTV.ng"]="https://www.youtube.com/ChannelsTelevision/live"
            ["nta|NTA International|https://marvellye.github.io/iptv/images/NTA.png|News|NTA.ng"]="https://www.youtube.com/c/NTALive/live"
            ["fox-news|FOX News|https://marvellye.github.io/iptv/images/FOX_News.png|News|FoxNews.ng"]="https://www.youtube.com/livenowfox/live"
            ["abc-news|ABC News|https://marvellye.github.io/iptv/images/ABC_News.png|News|ABCNews.go.com"]="https://www.youtube.com/ABCNews/live"
            ["france24-en|France 24 (in English)|https://marvellye.github.io/iptv/images/France24.png|News|France24.com/en/"]="https://www.youtube.com/@France24_en/live"
            ["dw-news|DW News|https://marvellye.github.io/iptv/images/DW_News.png|News|DW.com/en/"]="https://www.youtube.com/@dwnews/live"
          )

          for META in "${!CHANNELS[@]}"; do
            URL=${CHANNELS[$META]}
            FILE=$(echo "$META" | cut -d'|' -f1)
            NAME=$(echo "$META" | cut -d'|' -f2)
            LOGO=$(echo "$META" | cut -d'|' -f3)
            GROUP=$(echo "$META" | cut -d'|' -f4)
            TVGID=$(echo "$META" | cut -d'|' -f5)

            echo "#EXTM3U" > sources/$FILE.m3u

            echo ">>> Checking formats for $NAME ($URL)"
            yt-dlp --cookies cookies.txt -F "$URL" || true

            echo ">>> Trying to fetch stream link for $NAME"
            M3U_URL=$(yt-dlp --cookies cookies.txt -g -f "301/300/94/93/92/91" "$URL" || \
                      yt-dlp --cookies cookies.txt -g -f best "$URL" || echo "")

            if [ -n "$M3U_URL" ]; then
              echo ">>> Got stream URL for $NAME: $M3U_URL"
              echo "#EXTINF:-1 tvg-id=\"$TVGID\" tvg-logo=\"$LOGO\" group-title=\"$GROUP\",$NAME" >> sources/$FILE.m3u
              echo "$M3U_URL" >> sources/$FILE.m3u
            else
              echo ">>> Failed to fetch stream for $NAME, marking as offline"
              echo "#EXTINF:-1 tvg-id=\"$TVGID\" tvg-logo=\"$LOGO\" group-title=\"$GROUP\",$NAME (Unavailable)" >> sources/$FILE.m3u
              echo "http://offline" >> sources/$FILE.m3u
            fi
          done

      - name: Build master & playlist
        run: |
          # Build master: static + raw streams
          cp static.m3u master.m3u
          for f in sources/*.m3u; do
            tail -n +2 "$f" >> master.m3u
          done

          # Build playlist: static + references to sources (with metadata)
          cp static.m3u playlist.m3u
          for f in sources/*.m3u; do
            FILE=$(basename "$f")
            EXTINF=$(grep -m1 "#EXTINF" "$f")
            echo "$EXTINF" >> playlist.m3u
            echo "https://raw.githubusercontent.com/${{ github.repository }}/main/sources/$FILE" >> playlist.m3u
          done

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update IPTV playlist" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add master.m3u playlist.m3u sources/*.m3u
            git commit -m "Auto update IPTV playlist" || echo "No changes"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main